package com.hiczp.telegram.bot.application.context

import com.hiczp.telegram.bot.protocol.event.MessageEvent
import com.hiczp.telegram.bot.protocol.form.*
import com.hiczp.telegram.bot.protocol.model.*
import com.hiczp.telegram.bot.protocol.type.InputFile
import com.hiczp.telegram.bot.protocol.type.TelegramResponse
import io.ktor.client.request.forms.*

suspend fun TelegramBotEventContext<MessageEvent>.sendPhoto(
    photo: InputFile,
    caption: String? = null,
    parseMode: String? = null,
    captionEntities: List<MessageEntity>? = null,
    showCaptionAboveMedia: Boolean? = null,
    hasSpoiler: Boolean? = null,
    disableNotification: Boolean? = null,
    protectContent: Boolean? = null,
    allowPaidBroadcast: Boolean? = null,
    messageEffectId: String? = null,
    suggestedPostParameters: SuggestedPostParameters? = null,
    replyParameters: ReplyParameters? = null,
    replyMarkup: ReplyMarkup? = null,
) = client.sendPhoto(
    businessConnectionId = event.message.businessConnectionId,
    chatId = event.message.chat.id.toString(),
    messageThreadId = event.message.messageThreadId,
    directMessagesTopicId = event.message.directMessagesTopic?.topicId,
    photo = photo,
    caption = caption,
    parseMode = parseMode,
    captionEntities = captionEntities,
    showCaptionAboveMedia = showCaptionAboveMedia,
    hasSpoiler = hasSpoiler,
    disableNotification = disableNotification,
    protectContent = protectContent,
    allowPaidBroadcast = allowPaidBroadcast,
    messageEffectId = messageEffectId,
    suggestedPostParameters = suggestedPostParameters,
    replyParameters = replyParameters,
    replyMarkup = replyMarkup,
)

suspend fun TelegramBotEventContext<MessageEvent>.sendAudio(
    audio: InputFile,
    caption: String? = null,
    parseMode: String? = null,
    captionEntities: List<MessageEntity>? = null,
    duration: Long? = null,
    performer: String? = null,
    title: String? = null,
    thumbnail: InputFile? = null,
    disableNotification: Boolean? = null,
    protectContent: Boolean? = null,
    allowPaidBroadcast: Boolean? = null,
    messageEffectId: String? = null,
    suggestedPostParameters: SuggestedPostParameters? = null,
    replyParameters: ReplyParameters? = null,
    replyMarkup: ReplyMarkup? = null,
) = client.sendAudio(
    businessConnectionId = event.message.businessConnectionId,
    chatId = event.message.chat.id.toString(),
    messageThreadId = event.message.messageThreadId,
    directMessagesTopicId = event.message.directMessagesTopic?.topicId,
    audio = audio,
    caption = caption,
    parseMode = parseMode,
    captionEntities = captionEntities,
    duration = duration,
    performer = performer,
    title = title,
    thumbnail = thumbnail,
    disableNotification = disableNotification,
    protectContent = protectContent,
    allowPaidBroadcast = allowPaidBroadcast,
    messageEffectId = messageEffectId,
    suggestedPostParameters = suggestedPostParameters,
    replyParameters = replyParameters,
    replyMarkup = replyMarkup,
)

suspend fun TelegramBotEventContext<MessageEvent>.sendDocument(
    document: InputFile,
    thumbnail: InputFile? = null,
    caption: String? = null,
    parseMode: String? = null,
    captionEntities: List<MessageEntity>? = null,
    disableContentTypeDetection: Boolean? = null,
    disableNotification: Boolean? = null,
    protectContent: Boolean? = null,
    allowPaidBroadcast: Boolean? = null,
    messageEffectId: String? = null,
    suggestedPostParameters: SuggestedPostParameters? = null,
    replyParameters: ReplyParameters? = null,
    replyMarkup: ReplyMarkup? = null,
) = client.sendDocument(
    businessConnectionId = event.message.businessConnectionId,
    chatId = event.message.chat.id.toString(),
    messageThreadId = event.message.messageThreadId,
    directMessagesTopicId = event.message.directMessagesTopic?.topicId,
    document = document,
    thumbnail = thumbnail,
    caption = caption,
    parseMode = parseMode,
    captionEntities = captionEntities,
    disableContentTypeDetection = disableContentTypeDetection,
    disableNotification = disableNotification,
    protectContent = protectContent,
    allowPaidBroadcast = allowPaidBroadcast,
    messageEffectId = messageEffectId,
    suggestedPostParameters = suggestedPostParameters,
    replyParameters = replyParameters,
    replyMarkup = replyMarkup,
)

suspend fun TelegramBotEventContext<MessageEvent>.sendVideo(
    video: InputFile,
    duration: Long? = null,
    width: Long? = null,
    height: Long? = null,
    thumbnail: InputFile? = null,
    cover: InputFile? = null,
    startTimestamp: Long? = null,
    caption: String? = null,
    parseMode: String? = null,
    captionEntities: List<MessageEntity>? = null,
    showCaptionAboveMedia: Boolean? = null,
    hasSpoiler: Boolean? = null,
    supportsStreaming: Boolean? = null,
    disableNotification: Boolean? = null,
    protectContent: Boolean? = null,
    allowPaidBroadcast: Boolean? = null,
    messageEffectId: String? = null,
    suggestedPostParameters: SuggestedPostParameters? = null,
    replyParameters: ReplyParameters? = null,
    replyMarkup: ReplyMarkup? = null,
) = client.sendVideo(
    businessConnectionId = event.message.businessConnectionId,
    chatId = event.message.chat.id.toString(),
    messageThreadId = event.message.messageThreadId,
    directMessagesTopicId = event.message.directMessagesTopic?.topicId,
    video = video,
    duration = duration,
    width = width,
    height = height,
    thumbnail = thumbnail,
    cover = cover,
    startTimestamp = startTimestamp,
    caption = caption,
    parseMode = parseMode,
    captionEntities = captionEntities,
    showCaptionAboveMedia = showCaptionAboveMedia,
    hasSpoiler = hasSpoiler,
    supportsStreaming = supportsStreaming,
    disableNotification = disableNotification,
    protectContent = protectContent,
    allowPaidBroadcast = allowPaidBroadcast,
    messageEffectId = messageEffectId,
    suggestedPostParameters = suggestedPostParameters,
    replyParameters = replyParameters,
    replyMarkup = replyMarkup,
)

suspend fun TelegramBotEventContext<MessageEvent>.sendAnimation(
    animation: InputFile,
    duration: Long? = null,
    width: Long? = null,
    height: Long? = null,
    thumbnail: InputFile? = null,
    caption: String? = null,
    parseMode: String? = null,
    captionEntities: List<MessageEntity>? = null,
    showCaptionAboveMedia: Boolean? = null,
    hasSpoiler: Boolean? = null,
    disableNotification: Boolean? = null,
    protectContent: Boolean? = null,
    allowPaidBroadcast: Boolean? = null,
    messageEffectId: String? = null,
    suggestedPostParameters: SuggestedPostParameters? = null,
    replyParameters: ReplyParameters? = null,
    replyMarkup: ReplyMarkup? = null,
) = client.sendAnimation(
    businessConnectionId = event.message.businessConnectionId,
    chatId = event.message.chat.id.toString(),
    messageThreadId = event.message.messageThreadId,
    directMessagesTopicId = event.message.directMessagesTopic?.topicId,
    animation = animation,
    duration = duration,
    width = width,
    height = height,
    thumbnail = thumbnail,
    caption = caption,
    parseMode = parseMode,
    captionEntities = captionEntities,
    showCaptionAboveMedia = showCaptionAboveMedia,
    hasSpoiler = hasSpoiler,
    disableNotification = disableNotification,
    protectContent = protectContent,
    allowPaidBroadcast = allowPaidBroadcast,
    messageEffectId = messageEffectId,
    suggestedPostParameters = suggestedPostParameters,
    replyParameters = replyParameters,
    replyMarkup = replyMarkup,
)

suspend fun TelegramBotEventContext<MessageEvent>.sendVoice(
    voice: InputFile,
    caption: String? = null,
    parseMode: String? = null,
    captionEntities: List<MessageEntity>? = null,
    duration: Long? = null,
    disableNotification: Boolean? = null,
    protectContent: Boolean? = null,
    allowPaidBroadcast: Boolean? = null,
    messageEffectId: String? = null,
    suggestedPostParameters: SuggestedPostParameters? = null,
    replyParameters: ReplyParameters? = null,
    replyMarkup: ReplyMarkup? = null,
) = client.sendVoice(
    businessConnectionId = event.message.businessConnectionId,
    chatId = event.message.chat.id.toString(),
    messageThreadId = event.message.messageThreadId,
    directMessagesTopicId = event.message.directMessagesTopic?.topicId,
    voice = voice,
    caption = caption,
    parseMode = parseMode,
    captionEntities = captionEntities,
    duration = duration,
    disableNotification = disableNotification,
    protectContent = protectContent,
    allowPaidBroadcast = allowPaidBroadcast,
    messageEffectId = messageEffectId,
    suggestedPostParameters = suggestedPostParameters,
    replyParameters = replyParameters,
    replyMarkup = replyMarkup,
)

suspend fun TelegramBotEventContext<MessageEvent>.sendVideoNote(
    videoNote: InputFile,
    duration: Long? = null,
    length: Long? = null,
    thumbnail: InputFile? = null,
    disableNotification: Boolean? = null,
    protectContent: Boolean? = null,
    allowPaidBroadcast: Boolean? = null,
    messageEffectId: String? = null,
    suggestedPostParameters: SuggestedPostParameters? = null,
    replyParameters: ReplyParameters? = null,
    replyMarkup: ReplyMarkup? = null,
) = client.sendVideoNote(
    businessConnectionId = event.message.businessConnectionId,
    chatId = event.message.chat.id.toString(),
    messageThreadId = event.message.messageThreadId,
    directMessagesTopicId = event.message.directMessagesTopic?.topicId,
    videoNote = videoNote,
    duration = duration,
    length = length,
    thumbnail = thumbnail,
    disableNotification = disableNotification,
    protectContent = protectContent,
    allowPaidBroadcast = allowPaidBroadcast,
    messageEffectId = messageEffectId,
    suggestedPostParameters = suggestedPostParameters,
    replyParameters = replyParameters,
    replyMarkup = replyMarkup,
)

suspend fun TelegramBotEventContext<MessageEvent>.sendMediaGroup(
    media: List<InputMedia>,
    disableNotification: Boolean? = null,
    protectContent: Boolean? = null,
    allowPaidBroadcast: Boolean? = null,
    messageEffectId: String? = null,
    replyParameters: ReplyParameters? = null,
    attachments: List<FormPart<ChannelProvider>>? = null,
): TelegramResponse<List<Message>> = client.sendMediaGroup(
    businessConnectionId = event.message.businessConnectionId,
    chatId = event.message.chat.id.toString(),
    messageThreadId = event.message.messageThreadId,
    directMessagesTopicId = event.message.directMessagesTopic?.topicId,
    media = media,
    disableNotification = disableNotification,
    protectContent = protectContent,
    allowPaidBroadcast = allowPaidBroadcast,
    messageEffectId = messageEffectId,
    replyParameters = replyParameters,
    attachments = attachments,
)

suspend fun TelegramBotEventContext<MessageEvent>.sendLocation(
    latitude: Double,
    longitude: Double,
    horizontalAccuracy: Double? = null,
    livePeriod: Long? = null,
    heading: Long? = null,
    proximityAlertRadius: Long? = null,
    disableNotification: Boolean? = null,
    protectContent: Boolean? = null,
    allowPaidBroadcast: Boolean? = null,
    messageEffectId: String? = null,
    suggestedPostParameters: SuggestedPostParameters? = null,
    replyParameters: ReplyParameters? = null,
    replyMarkup: ReplyMarkup? = null,
) = client.sendLocation(
    businessConnectionId = event.message.businessConnectionId,
    chatId = event.message.chat.id.toString(),
    messageThreadId = event.message.messageThreadId,
    directMessagesTopicId = event.message.directMessagesTopic?.topicId,
    latitude = latitude,
    longitude = longitude,
    horizontalAccuracy = horizontalAccuracy,
    livePeriod = livePeriod,
    heading = heading,
    proximityAlertRadius = proximityAlertRadius,
    disableNotification = disableNotification,
    protectContent = protectContent,
    allowPaidBroadcast = allowPaidBroadcast,
    messageEffectId = messageEffectId,
    suggestedPostParameters = suggestedPostParameters,
    replyParameters = replyParameters,
    replyMarkup = replyMarkup,
)

suspend fun TelegramBotEventContext<MessageEvent>.sendVenue(
    latitude: Double,
    longitude: Double,
    title: String,
    address: String,
    foursquareId: String? = null,
    foursquareType: String? = null,
    googlePlaceId: String? = null,
    googlePlaceType: String? = null,
    disableNotification: Boolean? = null,
    protectContent: Boolean? = null,
    allowPaidBroadcast: Boolean? = null,
    messageEffectId: String? = null,
    suggestedPostParameters: SuggestedPostParameters? = null,
    replyParameters: ReplyParameters? = null,
    replyMarkup: ReplyMarkup? = null,
) = client.sendVenue(
    businessConnectionId = event.message.businessConnectionId,
    chatId = event.message.chat.id.toString(),
    messageThreadId = event.message.messageThreadId,
    directMessagesTopicId = event.message.directMessagesTopic?.topicId,
    latitude = latitude,
    longitude = longitude,
    title = title,
    address = address,
    foursquareId = foursquareId,
    foursquareType = foursquareType,
    googlePlaceId = googlePlaceId,
    googlePlaceType = googlePlaceType,
    disableNotification = disableNotification,
    protectContent = protectContent,
    allowPaidBroadcast = allowPaidBroadcast,
    messageEffectId = messageEffectId,
    suggestedPostParameters = suggestedPostParameters,
    replyParameters = replyParameters,
    replyMarkup = replyMarkup,
)

suspend fun TelegramBotEventContext<MessageEvent>.sendContact(
    phoneNumber: String,
    firstName: String,
    lastName: String? = null,
    vcard: String? = null,
    disableNotification: Boolean? = null,
    protectContent: Boolean? = null,
    allowPaidBroadcast: Boolean? = null,
    messageEffectId: String? = null,
    suggestedPostParameters: SuggestedPostParameters? = null,
    replyParameters: ReplyParameters? = null,
    replyMarkup: ReplyMarkup? = null,
) = client.sendContact(
    businessConnectionId = event.message.businessConnectionId,
    chatId = event.message.chat.id.toString(),
    messageThreadId = event.message.messageThreadId,
    directMessagesTopicId = event.message.directMessagesTopic?.topicId,
    phoneNumber = phoneNumber,
    firstName = firstName,
    lastName = lastName,
    vcard = vcard,
    disableNotification = disableNotification,
    protectContent = protectContent,
    allowPaidBroadcast = allowPaidBroadcast,
    messageEffectId = messageEffectId,
    suggestedPostParameters = suggestedPostParameters,
    replyParameters = replyParameters,
    replyMarkup = replyMarkup,
)

suspend fun TelegramBotEventContext<MessageEvent>.sendPoll(
    question: String,
    options: List<InputPollOption>,
    questionParseMode: String? = null,
    questionEntities: List<MessageEntity>? = null,
    isAnonymous: Boolean? = null,
    type: String? = null,
    allowsMultipleAnswers: Boolean? = null,
    correctOptionId: Long? = null,
    explanation: String? = null,
    explanationParseMode: String? = null,
    explanationEntities: List<MessageEntity>? = null,
    openPeriod: Long? = null,
    closeDate: Long? = null,
    isClosed: Boolean? = null,
    disableNotification: Boolean? = null,
    protectContent: Boolean? = null,
    allowPaidBroadcast: Boolean? = null,
    messageEffectId: String? = null,
    replyParameters: ReplyParameters? = null,
    replyMarkup: ReplyMarkup? = null,
) = client.sendPoll(
    businessConnectionId = event.message.businessConnectionId,
    chatId = event.message.chat.id.toString(),
    messageThreadId = event.message.messageThreadId,
    question = question,
    questionParseMode = questionParseMode,
    questionEntities = questionEntities,
    options = options,
    isAnonymous = isAnonymous,
    type = type,
    allowsMultipleAnswers = allowsMultipleAnswers,
    correctOptionId = correctOptionId,
    explanation = explanation,
    explanationParseMode = explanationParseMode,
    explanationEntities = explanationEntities,
    openPeriod = openPeriod,
    closeDate = closeDate,
    isClosed = isClosed,
    disableNotification = disableNotification,
    protectContent = protectContent,
    allowPaidBroadcast = allowPaidBroadcast,
    messageEffectId = messageEffectId,
    replyParameters = replyParameters,
    replyMarkup = replyMarkup,
)

suspend fun TelegramBotEventContext<MessageEvent>.sendDice(
    emoji: String? = null,
    disableNotification: Boolean? = null,
    protectContent: Boolean? = null,
    allowPaidBroadcast: Boolean? = null,
    messageEffectId: String? = null,
    suggestedPostParameters: SuggestedPostParameters? = null,
    replyParameters: ReplyParameters? = null,
    replyMarkup: ReplyMarkup? = null,
) = client.sendDice(
    businessConnectionId = event.message.businessConnectionId,
    chatId = event.message.chat.id.toString(),
    messageThreadId = event.message.messageThreadId,
    directMessagesTopicId = event.message.directMessagesTopic?.topicId,
    emoji = emoji,
    disableNotification = disableNotification,
    protectContent = protectContent,
    allowPaidBroadcast = allowPaidBroadcast,
    messageEffectId = messageEffectId,
    suggestedPostParameters = suggestedPostParameters,
    replyParameters = replyParameters,
    replyMarkup = replyMarkup,
)

suspend fun TelegramBotEventContext<MessageEvent>.sendGame(
    gameShortName: String,
    disableNotification: Boolean? = null,
    protectContent: Boolean? = null,
    allowPaidBroadcast: Boolean? = null,
    messageEffectId: String? = null,
    replyParameters: ReplyParameters? = null,
    replyMarkup: InlineKeyboardMarkup? = null,
) = client.sendGame(
    businessConnectionId = event.message.businessConnectionId,
    chatId = event.message.chat.id,
    messageThreadId = event.message.messageThreadId,
    gameShortName = gameShortName,
    disableNotification = disableNotification,
    protectContent = protectContent,
    allowPaidBroadcast = allowPaidBroadcast,
    messageEffectId = messageEffectId,
    replyParameters = replyParameters,
    replyMarkup = replyMarkup,
)

suspend fun TelegramBotEventContext<MessageEvent>.sendMessage(
    text: String,
    parseMode: String? = null,
    entities: List<MessageEntity>? = null,
    linkPreviewOptions: LinkPreviewOptions? = null,
    disableNotification: Boolean? = null,
    protectContent: Boolean? = null,
    allowPaidBroadcast: Boolean? = null,
    messageEffectId: String? = null,
    suggestedPostParameters: SuggestedPostParameters? = null,
    replyParameters: ReplyParameters? = null,
    replyMarkup: ReplyMarkup? = null,
) = client.sendMessage(
    businessConnectionId = event.message.businessConnectionId,
    chatId = event.message.chat.id.toString(),
    messageThreadId = event.message.messageThreadId,
    directMessagesTopicId = event.message.directMessagesTopic?.topicId,
    text = text,
    parseMode = parseMode,
    entities = entities,
    linkPreviewOptions = linkPreviewOptions,
    disableNotification = disableNotification,
    protectContent = protectContent,
    allowPaidBroadcast = allowPaidBroadcast,
    messageEffectId = messageEffectId,
    suggestedPostParameters = suggestedPostParameters,
    replyParameters = replyParameters,
    replyMarkup = replyMarkup,
)

suspend fun TelegramBotEventContext<MessageEvent>.sendChatAction(
    action: String,
) = client.sendChatAction(
    businessConnectionId = event.message.businessConnectionId,
    chatId = event.message.chat.id.toString(),
    messageThreadId = event.message.messageThreadId,
    action = action,
).getOrThrow()
